# Generated by Django 4.2.2 on 2023-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='declaration',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='objective',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='skill',
            name='softskill',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='skill',
            name='techskill',
            field=models.TextField(blank=True, default=None),
        ),
    ]
