# Generated by Django 4.2.2 on 2023-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_skill_skill_profile_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puc',
            name='institute',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='skill',
            name='lang',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='sslc',
            name='institute',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='university',
            name='institute',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.EmailField(max_length=25),
        ),
    ]
