# Generated by Django 4.2.2 on 2023-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='pinterest',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='experiance',
            name='exp',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=90),
        ),
        migrations.AlterField(
            model_name='puc',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='puc',
            name='board',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='puc',
            name='marks',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sslc',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sslc',
            name='marks',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='board',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='university',
            name='marks',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
