# Generated by Django 4.2.2 on 2023-08-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_puc_name_alter_puc_year_alter_university_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sslc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='university',
            name='address',
        ),
        migrations.AlterField(
            model_name='puc',
            name='marks',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='sslc',
            name='marks',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='university',
            name='marks',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
    ]
